#!/bin/sh

# Copyright (c) 2018-2025, Firas Khalil Khana
# Distributed under the terms of the ISC License

exec ./configure \
  --prefix=/usr \
  --sbindir=/usr/bin \
  --libexecdir=/usr/lib \
  --sysconfdir=/etc \
  --sharedstatedir=/var/lib \
  --localstatedir=/var \
  --runstatedir=/run \
  --libdir=/usr/lib \
  "$@"
