#!/bin/sh

# SPDX-License-Identifier: MPL-2.0
# Copyright © 2018-2025 Firas Khana

# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

exec ./configure \
  --prefix=/usr \
  --exec-prefix=/usr \
  --bindir=/usr/bin \
  --sbindir=/usr/bin \
  --libexecdir=/usr/lib \
  --sysconfdir=/etc \
  --sharedstatedir=/var/lib \
  --localstatedir=/var \
  --runstatedir=/run \
  --libdir=/usr/lib \
  "$@"
