#!/bin/sh -e

# Copyright (c) 2018-2023, Firas Khalil Khana
# Distributed under the terms of the ISC License

exec muon setup \
  -Dprefix=/usr \
  -Dbindir=/usr/bin \
  -Ddatadir=/usr/share \
  -Dincludedir=/usr/include \
  -Dinfodir=/usr/share/info \
  -Dlibdir=/usr/lib \
  -Dlibexecdir=/usr/lib/$nom \
  -Dlocaledir=/usr/share/locale \
  -Dmandir=/usr/share/man \
  -Dsbindir=/usr/bin \
  -Dsharedstatedir=/var/lib \
  -Dsysconfdir=/etc \
  -Dbackend=ninja \
  -Dbuildtype=release \
  -Dstdsplit=true \
  -Dstrip=true \
  -Dwrap_mode=nodownload \
  -Db_lto=true \
  -Db_lto_mode=thin \
  -Db_pie=true \
  $@
