#!/bin/sh

# SPDX-License-Identifier: MPL-2.0
# Copyright © 2018-2025 Firas Khana

# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

f=-std=c89

for i; do
  case $i in
    -ansi | $f | -std=iso9899:1990) f= ;;
    -std=*) echo "c89 called with non ANSI/ISO C option $i" >&2; exit 1 ;;
  esac
done

exec gcc $f "$@"
