#!/bin/sh

# Copyright (c) 2018-2025, Firas Khalil Khana
# Distributed under the terms of the ISC License

f=-std=c99

for i; do
  case $i in
    -std=c9[9x] | -std=iso9899:199[9x]) f= ;;
    -ansi | -std=*) echo "c99 called with non ISO C99 option $i" >&2; exit 1 ;;
  esac
done

exec gcc $f "$@"
