#!/bin/sh

# SPDX-License-Identifier: MPL-2.0
# Copyright © 2018-2025 Firas Khana

# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

f=-std=c99

for i; do
  case $i in
    -std=c9[9x] | -std=iso9899:199[9x]) f= ;;
    -ansi | -std=*) echo "c99 called with non ISO C99 option $i" >&2; exit 1 ;;
  esac
done

exec gcc $f "$@"
