#!/bin/sh

# Copyright (c) 2018-2025, Firas Khalil Khana
# Distributed under the terms of the ISC License

f=-std=c89

for i; do
  case $i in
    -ansi | $f | -std=iso9899:1990) f= ;;
    -std=*) echo "c89 called with non ANSI/ISO C option $i" >&2; exit 1 ;;
  esac
done

exec gcc $f "$@"
