#!/bin/sh

# Copyright (c) 2018-2025, Firas Khalil Khana
# Distributed under the terms of the ISC License

exec cmake \
  -DCMAKE_BUILD_TYPE=Release \
  -DCMAKE_INSTALL_PREFIX=/usr \
  -DCMAKE_INSTALL_SHAREDSTATEDIR=/var/lib \
  -G Ninja \
  "$@"
