#!/bin/sh

# Copyright (c) 2018-2025, Firas Khalil Khana
# Distributed under the terms of the ISC License

exec ./configure \
  --prefix=/usr \
  --exec-prefix=/usr \
  --bindir=/usr/bin \
  --sbindir=/usr/bin \
  --libexecdir=/usr/bin \
  --sysconfdir=/etc \
  --sharedstatedir=/var/lib \
  --localstatedir=/var \
  --runstatedir=/run \
  --libdir=/usr/lib \
  --includedir=/usr/include \
  --oldincludedir=/usr/include \
  --datarootdir=/usr/share \
  --datadir=/usr/share \
  --infodir=/usr/share/info \
  --localedir=/usr/share/locale \
  --mandir=/usr/share/man \
  "$@"
