#!/bin/sh

# Copyright (c) 2018-2025, Firas Khalil Khana
# Distributed under the terms of the ISC License

exec muon setup \
  -Dprefix=/usr \
  -Dbindir=/usr/bin \
  -Dsbindir=/usr/bin \
  -Dlibexecdir=/usr/lib \
  -Dsysconfdir=/etc \
  -Dsharedstatedir=/var/lib \
  -Dlocalstatedir=/var \
  -Dlibdir=/usr/lib \
  -Dauto_features=disabled \
  -Ddebug=false \
  -Ddefault_library=shared \
  -Doptimization=2 \
  -Dstrip=true \
  -Dwrap_mode=nodownload \
  -Db_lto=true \
  -Db_pie=true \
  "$@"
