#!/bin/sh

# Copyright (c) 2018-2025, Firas Khalil Khana
# Distributed under the terms of the ISC License

exec muon setup \
  -Dprefix=/usr \
  -Dsharedstatedir=/var/lib \
  -Dauto_features=disabled \
  -Ddebug=false \
  -Doptimization=2 \
  -Dstrip=true \
  -Dwrap_mode=nodownload \
  -Db_lto=true \
  -Db_pie=true \
  "$@"
