#!/bin/sh

# Copyright (c) 2018-2025, Firas Khalil Khana
# Distributed under the terms of the ISC License

case $# in
  0) /usr/lib/libc.so ;;
  1) /usr/lib/libc.so --list "$1" ;;
  *) for i in "$@"; do echo "$i:"; /usr/lib/libc.so --list "$i"; done ;;
esac
