#!/bin/sh

# SPDX-License-Identifier: MPL-2.0

# Copyright © 2018-2025 Firas Khana

# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

case $# in
  0) exec /usr/lib/libc.so ;;
  1) exec /usr/lib/libc.so --list "$1" ;;
  *) for i in "$@"; do echo "$i:"; /usr/lib/libc.so --list "$i"; done ;;
esac
